### ISSUE TITLE
How would I respond to a message? I get null

### ISSUE THREAD

**Issue by cederron** [Lunuy/react-penpal#2]
So parent is null, when called inside iframe method, like:

`
//   Parent 
const [childFrame, setChildFrame] = useState(null);

<Penpal
        src="http://localhost:3002"
        width={viewSize.sizePx}
        //height={"90vh"}
        setChild={setChildFrame}
        methods={{
          sendResponse( ) {
            console.log("lol");
          }  
        }}
        style={{
          border: "0",
          display: "block",
          margin: "0 auto",
          height:"90vh"
        }}
      />

...

childFrame.respondToParent();

`

`  
// iFrame

const [parent, setParent] = useState(null)

useEffect(() => {
    setTimeout( () =>{
      (async () => {
        const connection = connectToParent({
          methods: {
              respondToParent() {
                       parent.sendResponse(); //   <-----------------------   parent is null here
               }
          }
        });
        const con= await connection.promise;
        setParent(parent);
      })();
    }, 500);
  }, []); `

I dont know, it works if i call it outside of this method, so penpal is well set up.
I'm fairly new to react, so might be something I'm missing about scopes.

**Comment by Lunuy** [comment]
```js
const [parent, setParent] = useState(null);

useEffect(() => {
    setTimeout( () =>{
        (async () => {
            const connection = connectToParent({
                methods: {
                    respondToParent() {
                        parent.sendResponse(); // <----------------------- parent is null here
                    }
                }
            });
            const con = await connection.promise;
            setParent(parent);
        })();
    }, 500);
}, []);
```

The point of this problem is variable `parent`'s value is fixed when the functional component runs.

When the functional component run first time, value of `parent` is `null`.
So, at aspect of the function that used in `useEffect`, value of `parent` is fixed to null.

When `setParent` called, the component will be re-executed and value of `parent` will be not null.
But it does not mean the function that used in `useEffect` can detect value of `parent` changed.

First render execution and second one is two separate function call.

Maybe next example may help you:
```js
let state = 1;
let getState = () => state;

function f() {
    const state = getState();
    return x => (state + x);
}

const plus1 = f();
console.log(plus1(3));

state = 2;
const plus2 = f();
console.log(plus2(4));

// But, function of plus1 is not affected; because `state` value is fixed at aspect of the anonymous function.
console.log(plus1(5));
```



So, what you have to do is changing code like this:
```js
const parentRef = useRef(null);

useEffect(() => {
    setTimeout( () =>{
        (async () => {
            const connection = connectToParent({
                methods: {
                    respondToParent() {
                        parentRef.current.sendResponse();
                    }
                }
            });
            const con = await connection.promise;
            parentRef.current = parent;
        })();
    }, 500);
}, []);
```
`useRef` creates normal object that does not cause re-rendering.
The object can be used to share same values between multiple functional component executions.

**Comment by cederron** [comment]
> 

Thanks for the explanation, got to learn more about useRef (well react in general :) )
It is working now, thanks
